version: '3'

services:
  service.chain:
    build:
      context: .
      dockerfile: Dockerfile.seedService
    environment:
      - LOCAL_USER_ID
    volumes:
      - seed:/chain.seeded
      - ./Scripts:/Scripts
    command: /Scripts/cluster/pre.up
  bs:
    build:
      context: .
      dockerfile: Dockerfile.bs
    ports:
      - "3142"
    environment:
      - LOCAL_USER_ID
    volumes:
      - seed:/chain.seeded
      - ./Scripts:/Scripts
    depends_on: [service.chain]
    command: /bin/sh -c /Scripts/cluster/bs.start
  hc:
    build:
      context: .
      dockerfile: Dockerfile.serveInstance
    ports:
      - "3141"
      - "6283"
    environment:
      - LOCAL_USER_ID
    volumes:
      - seed:/chain.seeded
      - ./Scripts:/Scripts
    command: /Scripts/cluster/hc.sync
    #command: /bin/sh
    depends_on: [service.chain]
  hc.post.up:
    build:
      context: .
      dockerfile: Dockerfile.hc.post.up
    environment:
      - LOCAL_USER_ID
    volumes:
      - seed:/chain.seeded
      - ./Scripts:/Scripts
    command: /Scripts/cluster/post.up
    depends_on: [hc]

volumes:
  seed:
